version: "3"
volumes: 
  mysql-data:
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - 80:80
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./pub:/home/n9e/pub
  api:
    build: .
    image: api

  monapi:
    image: api
    restart: always
    command: monapi
    volumes: 
      - ./docker/etc:/app/etc
    ports: 
      - 5800:5800

  index:
    image: api
    restart: always
    command: index
    volumes: 
      - ./docker/etc:/app/etc
    ports: 
      - 5830:5830
      - 5831:5831

  transfer:
    image: api
    restart: always
    command: transfer
    volumes: 
      - ./docker/etc:/app/etc
    ports: 
      - 5810:5810
      - 5811:5811
      
  # web:
  #   build:
  #     context: web
  #   restart: always
  #   command: npm run dev
  #   ports: 
  #     - 8010:8010

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports: 
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  
    